version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: akna_motors_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aknamotors
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akna_motors_api
    restart: always
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/aknamotors?schema=public"
      JWT_SECRET: super-secret-jwt-key-akna-motors
      JWT_EXPIRATION: 1d
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres_data:
